# Generated by Django 4.1.1 on 2022-10-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('sexo', models.IntegerField(choices=[[0, 'Masculino'], [1, 'Femenino'], [2, 'Otro']])),
            ],
        ),
    ]
