# Generated by Django 4.1.1 on 2022-10-26 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Cocina', 'COCINA'), ('Limpieza', 'LIMPIEZA'), ('Accesorios', 'ACCESORIOS'), ('Hogar', 'HOGAR')], max_length=20)),
            ],
            options={
                'verbose_name': 'categoriaProducto',
                'verbose_name_plural': 'categoriaProductos',
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='sexo',
            field=models.IntegerField(choices=[[0, 'Masculino'], [1, 'Femenino'], [2, 'Otro']], default=0),
        ),
        migrations.CreateModel(
            name='infoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField(max_length=200)),
                ('disponibilidad', models.BooleanField()),
                ('categoriaProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_models.categoriaproducto')),
            ],
            options={
                'verbose_name': 'infoProducto',
                'verbose_name_plural': 'infoProductos',
            },
        ),
    ]
